import "./globals.css";

import { cn } from "@/lib/utils";
import Providers from "@/providers";
import type { Metadata } from "next";
import { Toaster } from "@/components/ui/sonner";
import { Inter as FontSans } from "next/font/google";

const fontSans = FontSans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "NextAuth SaaS",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn("min-h-screen bg-background antialiased", fontSans.className)}>
        <Providers>{children}</Providers>
        <Toaster />
      </body>
    </html>
  );
}
